// Generated by build_stimuli.py on 2026-09-28 12:34. Do not edit by hand.
window.STUDY.design.block1Conditions = ["avatar", "reference"];
window.STUDY.practice = [
 {
  "id": "prac_02-01",
  "sample_id": "02-01",
  "turkish": "O işe gelmedi.",
  "category": "plain",
  "reference_gloss": "O İŞ GELMEK^DEĞİL",
  "predicted_gloss": "O İŞ GELMEK^DEĞİL",
  "rewritten_gloss": "O İŞ GELMEK DEĞİL",
  "conditions": {
   "avatar": {
    "video": "media/avatar/02-01.mp4",
    "segments": [
     {
      "gloss": "O",
      "token": "O",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.987
     },
     {
      "gloss": "İŞ",
      "token": "İŞ",
      "strategy": "direct",
      "kind": "",
      "start": 0.955,
      "end": 1.612
     },
     {
      "gloss": "GELMEK",
      "token": "GELMEK",
      "strategy": "direct",
      "kind": "",
      "start": 1.58,
      "end": 2.112
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 1.955,
      "end": 2.362
     }
    ]
   }
  }
 }
];
window.STUDY.items = [
 {
  "id": "it_1003-03",
  "sample_id": "1003-03",
  "turkish": "Ben müzik öğretmeniyim, ilkokul öğrencilerine derste flütü nasıl üfleyeceklerini anlattım.",
  "category": "agreement",
  "reference_gloss": "BEN MÜZİK ÖĞRETMEN BEN ÇOCUKLAR İLK OKUL İÇİN ÇOCUKLAR BEN FLÜT ÖĞRETMEK ÖĞRETMEK ÇOCUKLAR BİLMEK^DEĞİL HAVA ÜFLEMEK NASIL? BEN ANLATMAK ANLATMAK YÖNLENDİRMEK ÇOCUKLAR ÖĞRENMEK ÖĞRENMEK",
  "predicted_gloss": "BEN MÜZİK ÖĞRETMEN BEN İLKOKUL ÖĞRENCİLER ÖĞRETMEK ÖĞRETMEK FLÜT ÜFLEMEK ÖĞRETMEK ÖĞRETMEK",
  "rewritten_gloss": "BEN MÜZİK ÖĞRETMEN BEN İLKOKUL ÖĞRENCİLER IX3b 1ÖĞRETMEK3b 1ÖĞRETMEK3b FLÜT ÜFLEMEK ÖĞRETMEK ÖĞRETMEK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1003-03.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "MÜZİK",
      "token": "MÜZİK",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.528
     },
     {
      "gloss": "ÖĞRETMEN",
      "token": "ÖĞRETMEN",
      "strategy": "direct",
      "kind": "",
      "start": 1.497,
      "end": 2.07
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 2.247,
      "end": 2.778
     },
     {
      "gloss": "İLKOKUL",
      "token": "İLKOKUL",
      "strategy": "direct",
      "kind": "",
      "start": 2.747,
      "end": 3.403
     },
     {
      "gloss": "ÖĞRENCİLER",
      "token": "ÖĞRENCİLER",
      "strategy": "morphological",
      "kind": "",
      "start": 3.372,
      "end": 3.903
     },
     {
      "gloss": "İŞARET ET (3b)",
      "token": "IX3b",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 3.872,
      "end": 4.32
     },
     {
      "gloss": "ÖĞRETMEK (1→3b)",
      "token": "1ÖĞRETMEK3b",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 4.288,
      "end": 5.07
     },
     {
      "gloss": "FLÜT",
      "token": "FLÜT",
      "strategy": "direct",
      "kind": "",
      "start": 5.038,
      "end": 5.653
     },
     {
      "gloss": "ÜFLEMEK",
      "token": "ÜFLEMEK",
      "strategy": "direct",
      "kind": "",
      "start": 5.622,
      "end": 6.153
     },
     {
      "gloss": "ÖĞRETMEK",
      "token": "ÖĞRETMEK",
      "strategy": "direct",
      "kind": "",
      "start": 6.122,
      "end": 7.112
     }
    ]
   },
   "reference": {
    "video": "media/reference/1003-03.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1026-02",
  "sample_id": "1026-02",
  "turkish": "Arkadaşım beni evine davet etti. İki odalı, dar bir evde oturuyor. Sıkışarak oturabildik. Ben bu kadar dar bir evde oturamam.",
  "category": "agreement",
  "reference_gloss": "BEN ARKADAŞ DAVET ETMEK MİSAFİR GİTMEK EV DAR ODA İKİ KÜÇÜK GİRMEK (SIĞMAK) ZOR EV DAR GÖRE OTURMAK^DEĞİL BEN",
  "predicted_gloss": "BEN ARKADAŞ EV DAVET ETMEK BEN GİTMEK EV İÇ İKİ ODA DAR BEN SIKILMAK BEN BU EV OTURMAK^DEĞİL",
  "rewritten_gloss": "BEN ARKADAŞ IX3a EV IX3b 3aDAVET ETMEK3b BEN GİTMEK EV İÇ İKİ ODA DAR BEN SIKILMAK BEN BU EV OTURMAK DEĞİL",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1026-02.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "ARKADAŞ",
      "token": "ARKADAŞ",
      "strategy": "direct",
      "kind": "",
      "start": 0.788,
      "end": 1.32
     },
     {
      "gloss": "İŞARET ET (3a)",
      "token": "IX3a",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 1.288,
      "end": 1.737
     },
     {
      "gloss": "EV",
      "token": "EV",
      "strategy": "direct",
      "kind": "",
      "start": 1.705,
      "end": 2.278
     },
     {
      "gloss": "İŞARET ET (3b)",
      "token": "IX3b",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 2.247,
      "end": 2.695
     },
     {
      "gloss": "DAVET ETMEK (3a→3b)",
      "token": "3aDAVET ETMEK3b",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 2.663,
      "end": 3.403
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 3.58,
      "end": 4.112
     },
     {
      "gloss": "GİTMEK",
      "token": "GİTMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 4.08,
      "end": 4.612
     },
     {
      "gloss": "EV",
      "token": "EV",
      "strategy": "direct",
      "kind": "",
      "start": 4.58,
      "end": 5.153
     },
     {
      "gloss": "İÇ",
      "token": "İÇ",
      "strategy": "direct",
      "kind": "",
      "start": 5.122,
      "end": 5.653
     },
     {
      "gloss": "İKİ",
      "token": "İKİ",
      "strategy": "direct",
      "kind": "",
      "start": 5.622,
      "end": 6.153
     },
     {
      "gloss": "ODA",
      "token": "ODA",
      "strategy": "direct",
      "kind": "",
      "start": 6.122,
      "end": 6.653
     },
     {
      "gloss": "DAR",
      "token": "DAR",
      "strategy": "sense",
      "kind": "oov",
      "start": 6.58,
      "end": 7.153
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 7.33,
      "end": 7.862
     },
     {
      "gloss": "SIKILMAK",
      "token": "SIKILMAK",
      "strategy": "direct",
      "kind": "",
      "start": 7.83,
      "end": 8.403
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 8.58,
      "end": 9.112
     },
     {
      "gloss": "BU",
      "token": "BU",
      "strategy": "direct",
      "kind": "",
      "start": 8.955,
      "end": 9.487
     },
     {
      "gloss": "EV",
      "token": "EV",
      "strategy": "direct",
      "kind": "",
      "start": 9.455,
      "end": 10.028
     },
     {
      "gloss": "OTURMAK",
      "token": "OTURMAK",
      "strategy": "direct",
      "kind": "",
      "start": 9.997,
      "end": 10.57
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 10.413,
      "end": 10.82
     }
    ]
   },
   "reference": {
    "video": "media/reference/1026-02.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1052-03",
  "sample_id": "1052-03",
  "turkish": "Kar yağdığında çocuğun biri sürekli bana kar topu atıyordu, çok sinir oldum ve ona nişan alarak kar tapu ile onu tam hedeften vurdum.",
  "category": "agreement",
  "reference_gloss": "KAR YAĞMAK YAĞMAK ÇOCUK BEN (KAR TOPU) ATMAK ATMAK BEN GICIK OLMAK NİŞAN ALMAK BEN VURMAK",
  "predicted_gloss": "KAR YAĞMAK ÇOCUK KAR TOPU ATMAK ATMAK BEN SİNİRLENMEK BEN NİŞAN ALMAK ATMAK TAM VURMAK",
  "rewritten_gloss": "KAR YAĞMAK ÇOCUK KAR TOPU ATMAK ATMAK BEN SİNİRLENMEK BEN NİŞAN IX3b 1ALMAK3b ATMAK TAM VURMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1052-03.mp4",
    "segments": [
     {
      "gloss": "KAR",
      "token": "KAR",
      "strategy": "sense",
      "kind": "oov",
      "start": 0.413,
      "end": 1.07
     },
     {
      "gloss": "YAĞMAK",
      "token": "YAĞMAK",
      "strategy": "direct",
      "kind": "",
      "start": 1.247,
      "end": 1.778
     },
     {
      "gloss": "ÇOCUK",
      "token": "ÇOCUK",
      "strategy": "direct",
      "kind": "",
      "start": 1.747,
      "end": 2.278
     },
     {
      "gloss": "KAR",
      "token": "KAR",
      "strategy": "sense",
      "kind": "oov",
      "start": 2.205,
      "end": 2.82
     },
     {
      "gloss": "TOPU",
      "token": "TOPU",
      "strategy": "morphological",
      "kind": "",
      "start": 2.788,
      "end": 3.32
     },
     {
      "gloss": "ATMAK",
      "token": "ATMAK",
      "strategy": "direct",
      "kind": "",
      "start": 3.288,
      "end": 4.278
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 4.455,
      "end": 4.987
     },
     {
      "gloss": "SİNİRLENMEK",
      "token": "SİNİRLENMEK",
      "strategy": "direct",
      "kind": "",
      "start": 4.955,
      "end": 5.528
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 5.705,
      "end": 6.237
     },
     {
      "gloss": "NİŞAN",
      "token": "NİŞAN",
      "strategy": "sense",
      "kind": "oov",
      "start": 6.08,
      "end": 6.737
     },
     {
      "gloss": "İŞARET ET (3b)",
      "token": "IX3b",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 6.705,
      "end": 7.153
     },
     {
      "gloss": "ALMAK (1→3b)",
      "token": "1ALMAK3b",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 7.122,
      "end": 7.862
     },
     {
      "gloss": "ATMAK",
      "token": "ATMAK",
      "strategy": "direct",
      "kind": "",
      "start": 7.83,
      "end": 8.403
     },
     {
      "gloss": "TAM",
      "token": "TAM",
      "strategy": "direct",
      "kind": "",
      "start": 8.58,
      "end": 9.112
     },
     {
      "gloss": "VURMAK",
      "token": "VURMAK",
      "strategy": "sense",
      "kind": "oov",
      "start": 9.08,
      "end": 9.653
     }
    ]
   },
   "reference": {
    "video": "media/reference/1052-03.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1201-01",
  "sample_id": "1201-01",
  "turkish": "Tiyatro oyunumuz için on iki kişilik bir takım oluşturduk ve oyuna çalıştırdık. Herkes hazır olunca da insanları davet edip oyunumuzu sunduk.",
  "category": "agreement",
  "reference_gloss": "TİYATRO İÇİN ON İKİ KİŞİ SEÇMEK SEÇMEK TAKIM HAZIRLAMAK EĞİTMEK EĞİTMEK USTA OLMAK BİTMEK DAVET ETMEK OYNAMAK",
  "predicted_gloss": "TİYATRO OYUN İÇİN ONİKİ KİŞİ TAKIM OLMAK ÇALIŞMAK ÇALIŞMAK HAZIR OLMAK İNSANLAR DAVET ETMEK TİYATRO OYUN OYNAMAK",
  "rewritten_gloss": "TİYATRO OYUN İÇİN ONİKİ KİŞİ TAKIM OLMAK ÇALIŞMAK ÇALIŞMAK HAZIR OLMAK İNSANLAR IX3b 1DAVET ETMEK3b TİYATRO OYUN OYNAMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1201-01.mp4",
    "segments": [
     {
      "gloss": "TİYATRO",
      "token": "TİYATRO",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "OYUN",
      "token": "OYUN",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.528
     },
     {
      "gloss": "İÇİN",
      "token": "İÇİN",
      "strategy": "direct",
      "kind": "",
      "start": 1.455,
      "end": 1.987
     },
     {
      "gloss": "ONİKİ",
      "token": "ONİKİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.955,
      "end": 2.612
     },
     {
      "gloss": "KİŞİ",
      "token": "KİŞİ",
      "strategy": "direct",
      "kind": "",
      "start": 2.58,
      "end": 3.112
     },
     {
      "gloss": "TAKIM",
      "token": "TAKIM",
      "strategy": "direct",
      "kind": "",
      "start": 3.08,
      "end": 3.612
     },
     {
      "gloss": "OLMAK",
      "token": "OLMAK",
      "strategy": "direct",
      "kind": "",
      "start": 3.58,
      "end": 4.112
     },
     {
      "gloss": "ÇALIŞMAK",
      "token": "ÇALIŞMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.08,
      "end": 4.987
     },
     {
      "gloss": "HAZIR",
      "token": "HAZIR",
      "strategy": "direct",
      "kind": "",
      "start": 4.955,
      "end": 5.57
     },
     {
      "gloss": "OLMAK",
      "token": "OLMAK",
      "strategy": "direct",
      "kind": "",
      "start": 5.538,
      "end": 6.112
     },
     {
      "gloss": "İNSANLAR",
      "token": "İNSANLAR",
      "strategy": "morphological",
      "kind": "",
      "start": 6.288,
      "end": 6.945
     },
     {
      "gloss": "İŞARET ET (3b)",
      "token": "IX3b",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 6.913,
      "end": 7.362
     },
     {
      "gloss": "DAVET ETMEK (1→3b)",
      "token": "1DAVET ETMEK3b",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 7.33,
      "end": 8.07
     },
     {
      "gloss": "TİYATRO",
      "token": "TİYATRO",
      "strategy": "direct",
      "kind": "",
      "start": 8.038,
      "end": 8.57
     },
     {
      "gloss": "OYUN OYNAMAK",
      "token": "OYUN OYNAMAK",
      "strategy": "direct",
      "kind": "",
      "start": 8.497,
      "end": 9.153
     }
    ]
   },
   "reference": {
    "video": "media/reference/1201-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1217-01",
  "sample_id": "1217-01",
  "turkish": "Oğlum yüzmeyi bilmediği için sürekli batıyordu, şimdi ona öğrettim ve çok güzel yüzüyor.",
  "category": "agreement",
  "reference_gloss": "BEN OĞUL YÜZMEK BİLMEK^DEĞİL BATMAK BATMAK BEN EĞİTMEK ŞİMDİ İYİ YÜZMEK BATMAK YOK",
  "predicted_gloss": "BEN OĞUL YÜZMEK BİLMEK^DEĞİL YÜZMEK BİLMEK^DEĞİL YÜZMEK BİLMEK^DEĞİL BEN ÖĞRETMEK ÖĞRETMEK ŞİMDİ YÜZMEK B",
  "rewritten_gloss": "BEN OĞUL YÜZMEK BİLMEK DEĞİL YÜZMEK BİLMEK DEĞİL YÜZMEK BİLMEK DEĞİL IX3a BEN 3aÖĞRETMEK1 3aÖĞRETMEK1 ŞİMDİ YÜZMEK B",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1217-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "OĞUL",
      "token": "OĞUL",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.487
     },
     {
      "gloss": "YÜZMEK",
      "token": "YÜZMEK",
      "strategy": "direct",
      "kind": "",
      "start": 1.33,
      "end": 1.903
     },
     {
      "gloss": "BİLMEK",
      "token": "BİLMEK",
      "strategy": "direct",
      "kind": "",
      "start": 2.08,
      "end": 2.612
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 2.788,
      "end": 3.195
     },
     {
      "gloss": "YÜZMEK",
      "token": "YÜZMEK",
      "strategy": "direct",
      "kind": "",
      "start": 3.163,
      "end": 3.737
     },
     {
      "gloss": "BİLMEK",
      "token": "BİLMEK",
      "strategy": "direct",
      "kind": "",
      "start": 3.913,
      "end": 4.445
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 4.622,
      "end": 5.028
     },
     {
      "gloss": "YÜZMEK",
      "token": "YÜZMEK",
      "strategy": "direct",
      "kind": "",
      "start": 4.997,
      "end": 5.57
     },
     {
      "gloss": "BİLMEK",
      "token": "BİLMEK",
      "strategy": "direct",
      "kind": "",
      "start": 5.747,
      "end": 6.278
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 6.455,
      "end": 6.862
     },
     {
      "gloss": "İŞARET ET (3a)",
      "token": "IX3a",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 6.83,
      "end": 7.278
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 7.455,
      "end": 7.987
     },
     {
      "gloss": "ÖĞRETMEK (3a→1)",
      "token": "3aÖĞRETMEK1",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 7.955,
      "end": 8.737
     },
     {
      "gloss": "ŞİMDİ",
      "token": "ŞİMDİ",
      "strategy": "direct",
      "kind": "",
      "start": 8.705,
      "end": 9.278
     },
     {
      "gloss": "YÜZMEK",
      "token": "YÜZMEK",
      "strategy": "direct",
      "kind": "",
      "start": 9.455,
      "end": 10.07
     }
    ]
   },
   "reference": {
    "video": "media/reference/1217-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1330-01",
  "sample_id": "1330-01",
  "turkish": "Kız kardeşim evlenirken damat tarafı gelin almaya geldiği zaman, kırmızı kurdele bağlandıktan sonra onu (evden) çıkardık.",
  "category": "agreement",
  "reference_gloss": "KIZ KARDEŞ EVLENMEK DAMAT TARAF AİLE GELMEK GELİN ALMAK MECBUR KIRMIZI KURDELE BAĞLAMAK GİTMEK",
  "predicted_gloss": "BEN KIZ KARDEŞ EVLENMEK DAMAT GELMEK GELİN ALMAK İÇİN ÖNCE KURDELE BAĞLAMAK BAĞLAMAK SONRA GELİN ÇIKARMAK",
  "rewritten_gloss": "BEN KIZ KARDEŞ EVLENMEK DAMAT GELMEK GELİN IX3b 1ALMAK3b İÇİN ÖNCE KURDELE BAĞLAMAK BAĞLAMAK SONRA GELİN ÇIKARMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1330-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "KIZ",
      "token": "KIZ",
      "strategy": "direct",
      "kind": "",
      "start": 0.788,
      "end": 1.32
     },
     {
      "gloss": "KARDEŞ",
      "token": "KARDEŞ",
      "strategy": "direct",
      "kind": "",
      "start": 1.288,
      "end": 1.82
     },
     {
      "gloss": "EVLENMEK",
      "token": "EVLENMEK",
      "strategy": "direct",
      "kind": "",
      "start": 1.788,
      "end": 2.32
     },
     {
      "gloss": "DAMAT",
      "token": "DAMAT",
      "strategy": "direct",
      "kind": "",
      "start": 2.288,
      "end": 2.82
     },
     {
      "gloss": "GELMEK",
      "token": "GELMEK",
      "strategy": "direct",
      "kind": "",
      "start": 2.788,
      "end": 3.362
     },
     {
      "gloss": "GELİN",
      "token": "GELİN",
      "strategy": "direct",
      "kind": "",
      "start": 3.538,
      "end": 4.07
     },
     {
      "gloss": "İŞARET ET (3b)",
      "token": "IX3b",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 4.038,
      "end": 4.487
     },
     {
      "gloss": "ALMAK (1→3b)",
      "token": "1ALMAK3b",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 4.455,
      "end": 5.195
     },
     {
      "gloss": "İÇİN",
      "token": "İÇİN",
      "strategy": "direct",
      "kind": "",
      "start": 5.163,
      "end": 5.695
     },
     {
      "gloss": "ÖNCE",
      "token": "ÖNCE",
      "strategy": "direct",
      "kind": "",
      "start": 5.663,
      "end": 6.195
     },
     {
      "gloss": "K-U-R-D-E-L-E",
      "token": "KURDELE",
      "strategy": "fingerspell",
      "kind": "fs",
      "start": 6.122,
      "end": 8.653
     },
     {
      "gloss": "BAĞLAMAK",
      "token": "BAĞLAMAK",
      "strategy": "sense",
      "kind": "oov",
      "start": 8.58,
      "end": 9.57
     },
     {
      "gloss": "SONRA",
      "token": "SONRA",
      "strategy": "direct",
      "kind": "",
      "start": 9.747,
      "end": 10.278
     },
     {
      "gloss": "GELİN",
      "token": "GELİN",
      "strategy": "direct",
      "kind": "",
      "start": 10.247,
      "end": 10.778
     },
     {
      "gloss": "ÇIKARMAK",
      "token": "ÇIKARMAK",
      "strategy": "sense",
      "kind": "oov",
      "start": 10.747,
      "end": 11.362
     }
    ]
   },
   "reference": {
    "video": "media/reference/1330-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1406-02",
  "sample_id": "1406-02",
  "turkish": "İşaret dilini öğrendikten sonra, öğretmenlik yapmaya başladım ve ilk ayak bastığım yer kolej oldu.",
  "category": "oov",
  "reference_gloss": "TÜRK İŞARET DİL ÖĞRETMEN OLMAK İSTEMEK KURS GİTMEK GELMEK GİTMEK GELMEK BELGE ALMAK BİTMEK İLK AYAK BASMAK KOLEJ ÖĞRENCİLER ÖĞRETMEK ÖĞRETMEK",
  "predicted_gloss": "BEN İŞARET DİL ÖĞRENMEK ÖĞRENMEK BİTMEK ÖĞRETMEN OLMAK İLK KOLEJ GİTMEK",
  "rewritten_gloss": "BEN İŞARET DİL ÖĞRENMEK ÖĞRENMEK BİTMEK ÖĞRETMEN OLMAK İLK KOLEJ GİTMEK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1406-02.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "İŞARET",
      "token": "İŞARET",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.57
     },
     {
      "gloss": "DİL",
      "token": "DİL",
      "strategy": "direct",
      "kind": "",
      "start": 1.538,
      "end": 2.07
     },
     {
      "gloss": "ÖĞRENMEK",
      "token": "ÖĞRENMEK",
      "strategy": "direct",
      "kind": "",
      "start": 2.038,
      "end": 2.945
     },
     {
      "gloss": "BİTMEK",
      "token": "BİTMEK",
      "strategy": "direct",
      "kind": "",
      "start": 2.913,
      "end": 3.57
     },
     {
      "gloss": "ÖĞRETMEN",
      "token": "ÖĞRETMEN",
      "strategy": "direct",
      "kind": "",
      "start": 3.622,
      "end": 4.153
     },
     {
      "gloss": "OLMAK",
      "token": "OLMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.122,
      "end": 4.695
     },
     {
      "gloss": "İLK",
      "token": "İLK",
      "strategy": "direct",
      "kind": "",
      "start": 4.872,
      "end": 5.403
     },
     {
      "gloss": "KOLEJ",
      "token": "KOLEJ",
      "strategy": "synonym",
      "kind": "oov",
      "start": 5.372,
      "end": 5.945
     },
     {
      "gloss": "GİTMEK",
      "token": "GİTMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 5.913,
      "end": 6.487
     }
    ]
   },
   "reference": {
    "video": "media/reference/1406-02.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1467-01",
  "sample_id": "1467-01",
  "turkish": "Arabamı temizlettikten sonra üzerini bezle örttüm. Yakında düğün var, kirlenmesini istemiyorum.",
  "category": "oov",
  "reference_gloss": "BEN ARABA TEMİZLEMEK HAZIR BEZ ÖRTMEK BİTMEK YAKIN CUMARTESİ DÜĞÜN VAR KİRLENMEK İZİN VERMEK^DEĞİL",
  "predicted_gloss": "BEN ARABA TEMİZLEMEK BİTMEK BEZ ÖRTMEK ÖRTMEK YAKIN DÜĞÜN VAR ARABA KİRLENMEK İSTEMEK^DEĞİL",
  "rewritten_gloss": "BEN ARABA TEMİZLEMEK BİTMEK BEZ ÖRTMEK ÖRTMEK YAKIN DÜĞÜN VAR ARABA KİRLENMEK İSTEMEK DEĞİL",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1467-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "ARABA",
      "token": "ARABA",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "TEMİZLEMEK",
      "token": "TEMİZLEMEK",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 1.987
     },
     {
      "gloss": "BİTMEK",
      "token": "BİTMEK",
      "strategy": "direct",
      "kind": "",
      "start": 2.163,
      "end": 2.778
     },
     {
      "gloss": "B-E-Z",
      "token": "BEZ",
      "strategy": "fingerspell",
      "kind": "fs",
      "start": 2.705,
      "end": 3.903
     },
     {
      "gloss": "ÖRTMEK",
      "token": "ÖRTMEK",
      "strategy": "direct",
      "kind": "",
      "start": 3.83,
      "end": 4.737
     },
     {
      "gloss": "YAKIN",
      "token": "YAKIN",
      "strategy": "direct",
      "kind": "",
      "start": 4.705,
      "end": 5.278
     },
     {
      "gloss": "DÜĞÜN",
      "token": "DÜĞÜN",
      "strategy": "direct",
      "kind": "",
      "start": 5.247,
      "end": 5.778
     },
     {
      "gloss": "VAR",
      "token": "VAR",
      "strategy": "direct",
      "kind": "",
      "start": 5.747,
      "end": 6.278
     },
     {
      "gloss": "ARABA",
      "token": "ARABA",
      "strategy": "direct",
      "kind": "",
      "start": 6.247,
      "end": 6.778
     },
     {
      "gloss": "KİRLENMEK",
      "token": "KİRLENMEK",
      "strategy": "synonym",
      "kind": "oov",
      "start": 6.747,
      "end": 7.278
     },
     {
      "gloss": "İSTEMEK",
      "token": "İSTEMEK",
      "strategy": "direct",
      "kind": "",
      "start": 7.122,
      "end": 7.653
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 7.497,
      "end": 7.903
     }
    ]
   },
   "reference": {
    "video": "media/reference/1467-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1503-01",
  "sample_id": "1503-01",
  "turkish": "Odadan henüz çıkmıştım ki, arkamdam birçok olay olmuş. Döndüğümde olanları anlattılar, ağzım açık kaldı.",
  "category": "oov",
  "reference_gloss": "BEN BEŞ DAKİKA YENİ ÇIKMAK ÇOK BÜYÜK OLAY BEN BİLMEK^DEĞİL GELMEK ANLATMAK BEN AĞIZ AÇIK KALMAK ŞOK OLMAK ŞOK OLMAK ŞOK OLMAK",
  "predicted_gloss": "BEN YENİ ODA ÇIKMAK ARKADA OLAY OLAY OLAY BEN DÖNMEK ANLATMAK ANLATMAK BEN AĞIZ AÇIK KALMAK",
  "rewritten_gloss": "BEN YENİ ODA ÇIKMAK ARKADA OLAY OLAY OLAY BEN DÖNMEK ANLATMAK ANLATMAK BEN AĞIZ AÇIK KALMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1503-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "YENİ",
      "token": "YENİ",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "ODA",
      "token": "ODA",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 1.945
     },
     {
      "gloss": "ÇIKMAK",
      "token": "ÇIKMAK",
      "strategy": "sense",
      "kind": "oov",
      "start": 1.913,
      "end": 2.487
     },
     {
      "gloss": "ARKADA",
      "token": "ARKADA",
      "strategy": "morphological",
      "kind": "",
      "start": 2.663,
      "end": 3.237
     },
     {
      "gloss": "OLAY",
      "token": "OLAY",
      "strategy": "direct",
      "kind": "",
      "start": 3.205,
      "end": 4.112
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 4.08,
      "end": 4.653
     },
     {
      "gloss": "DÖNMEK",
      "token": "DÖNMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 4.83,
      "end": 5.362
     },
     {
      "gloss": "ANLATMAK",
      "token": "ANLATMAK",
      "strategy": "direct",
      "kind": "",
      "start": 5.33,
      "end": 6.32
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 6.497,
      "end": 7.028
     },
     {
      "gloss": "AĞIZ",
      "token": "AĞIZ",
      "strategy": "direct",
      "kind": "",
      "start": 6.997,
      "end": 7.612
     },
     {
      "gloss": "AÇIK",
      "token": "AÇIK",
      "strategy": "direct",
      "kind": "",
      "start": 7.58,
      "end": 8.112
     },
     {
      "gloss": "KALMAK",
      "token": "KALMAK",
      "strategy": "sense",
      "kind": "oov",
      "start": 8.08,
      "end": 8.653
     }
    ]
   },
   "reference": {
    "video": "media/reference/1503-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1546-01",
  "sample_id": "1546-01",
  "turkish": "Eskiden çok hastaydım. Elhamdülillah iyileştim.",
  "category": "plain",
  "reference_gloss": "ESKİ HASTA HEP HEP ŞİMDİ HASTA İYİ ELHAMDÜLİLLAH",
  "predicted_gloss": "BEN ESKİ HASTA ÇOK FAZLA ŞİMDİ ELHAMDÜLİLLAH İYİLEŞMEK",
  "rewritten_gloss": "BEN ESKİ HASTA ÇOK FAZLA ŞİMDİ ELHAMDÜLİLLAH İYİLEŞMEK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1546-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "ESKİ",
      "token": "ESKİ",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "HASTA",
      "token": "HASTA",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 2.07
     },
     {
      "gloss": "ÇOK",
      "token": "ÇOK",
      "strategy": "direct",
      "kind": "",
      "start": 2.038,
      "end": 2.57
     },
     {
      "gloss": "FAZLA",
      "token": "FAZLA",
      "strategy": "direct",
      "kind": "",
      "start": 2.538,
      "end": 3.112
     },
     {
      "gloss": "ŞİMDİ",
      "token": "ŞİMDİ",
      "strategy": "direct",
      "kind": "",
      "start": 3.288,
      "end": 3.82
     },
     {
      "gloss": "ELHAMDÜLİLLAH",
      "token": "ELHAMDÜLİLLAH",
      "strategy": "direct",
      "kind": "",
      "start": 3.788,
      "end": 4.32
     },
     {
      "gloss": "İYİLEŞMEK",
      "token": "İYİLEŞMEK",
      "strategy": "direct",
      "kind": "",
      "start": 4.288,
      "end": 4.862
     }
    ]
   },
   "reference": {
    "video": "media/reference/1546-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1663-01",
  "sample_id": "1663-01",
  "turkish": "Amerika'nın yeni başkanı Trump oldu, bu nedenle herkes korkup kendi ülkesine kaçtı.",
  "category": "fingerspell",
  "reference_gloss": "AMERİKA O İÇİN YENİ BAŞKAN TRUMP OLMAK HERKES KENDİ UZAK DURMAK KORKMAK ÜLKE KAÇMAK KAÇMAK",
  "predicted_gloss": "AMERİKA YENİ BAŞKAN TRUMP OLMAK HERKES KORKMAK KAÇMAK KAÇMAK",
  "rewritten_gloss": "AMERİKA YENİ BAŞKAN TRUMP OLMAK HERKES KORKMAK KAÇMAK KAÇMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1663-01.mp4",
    "segments": [
     {
      "gloss": "AMERİKA",
      "token": "AMERİKA",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 1.028
     },
     {
      "gloss": "YENİ",
      "token": "YENİ",
      "strategy": "direct",
      "kind": "",
      "start": 0.997,
      "end": 1.528
     },
     {
      "gloss": "BAŞKAN",
      "token": "BAŞKAN",
      "strategy": "direct",
      "kind": "",
      "start": 1.497,
      "end": 2.028
     },
     {
      "gloss": "T-R-U-M-P",
      "token": "TRUMP",
      "strategy": "fingerspell",
      "kind": "fs",
      "start": 1.955,
      "end": 3.82
     },
     {
      "gloss": "OLMAK",
      "token": "OLMAK",
      "strategy": "direct",
      "kind": "",
      "start": 3.747,
      "end": 4.32
     },
     {
      "gloss": "HERKES",
      "token": "HERKES",
      "strategy": "direct",
      "kind": "",
      "start": 4.497,
      "end": 5.028
     },
     {
      "gloss": "KORKMAK",
      "token": "KORKMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.997,
      "end": 5.528
     },
     {
      "gloss": "KAÇMAK",
      "token": "KAÇMAK",
      "strategy": "direct",
      "kind": "",
      "start": 5.497,
      "end": 6.487
     }
    ]
   },
   "reference": {
    "video": "media/reference/1663-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1672-02",
  "sample_id": "1672-02",
  "turkish": "Arkadaşlarla birlikte Rize'ye gittik ve hep birlikte yaylaya çıktık. Havası ve manzarası çok güzeldi.",
  "category": "oov",
  "reference_gloss": "ARKADAŞ AHBAP BERABER RİZE GİTMEK HAVA YAYLA (TEPE) GİTMEK ARKADAŞ KABUL ETMEK GRUP YOL GİTMEK GİTMEK GELMEK ÇIKMAK ÇIKMAK EN TEPE HAVA SÜPER BAKMAK MANZARA GÜZEL",
  "predicted_gloss": "BEN ARKADAŞ GRUP BERABER RİZE GİTMEK YAYLA ÇIKMAK HAVA MANZARA GÜZEL",
  "rewritten_gloss": "BEN ARKADAŞ GRUP BERABER RİZE GİTMEK YAYLA ÇIKMAK HAVA MANZARA GÜZEL",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1672-02.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "ARKADAŞ",
      "token": "ARKADAŞ",
      "strategy": "direct",
      "kind": "",
      "start": 0.788,
      "end": 1.32
     },
     {
      "gloss": "GRUP",
      "token": "GRUP",
      "strategy": "direct",
      "kind": "",
      "start": 1.288,
      "end": 1.82
     },
     {
      "gloss": "BERABER",
      "token": "BERABER",
      "strategy": "direct",
      "kind": "",
      "start": 1.788,
      "end": 2.32
     },
     {
      "gloss": "RİZE",
      "token": "RİZE",
      "strategy": "direct",
      "kind": "",
      "start": 2.288,
      "end": 2.862
     },
     {
      "gloss": "GİTMEK",
      "token": "GİTMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 2.83,
      "end": 3.362
     },
     {
      "gloss": "YAYLA",
      "token": "YAYLA",
      "strategy": "direct",
      "kind": "",
      "start": 3.33,
      "end": 3.987
     },
     {
      "gloss": "ÇIKMAK",
      "token": "ÇIKMAK",
      "strategy": "sense",
      "kind": "oov",
      "start": 3.955,
      "end": 4.528
     },
     {
      "gloss": "HAVA",
      "token": "HAVA",
      "strategy": "direct",
      "kind": "",
      "start": 4.705,
      "end": 5.237
     },
     {
      "gloss": "MANZARA",
      "token": "MANZARA",
      "strategy": "direct",
      "kind": "",
      "start": 5.205,
      "end": 5.862
     },
     {
      "gloss": "GÜZEL",
      "token": "GÜZEL",
      "strategy": "direct",
      "kind": "",
      "start": 5.83,
      "end": 6.445
     }
    ]
   },
   "reference": {
    "video": "media/reference/1672-02.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1687-02",
  "sample_id": "1687-02",
  "turkish": "İnsanlara alçaltıcı davranılmamalıdır. Bütün insanlar eşittir.",
  "category": "plain",
  "reference_gloss": "İNSAN ALÇALMAK YAPMAK^DEĞİL İNSAN EŞİT LAZIM",
  "predicted_gloss": "İNSAN HEPSİ ALÇALMAK YAPMAK^DEĞİL EŞİT",
  "rewritten_gloss": "İNSAN HEPSİ ALÇALMAK YAPMAK DEĞİL EŞİT",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1687-02.mp4",
    "segments": [
     {
      "gloss": "İNSAN",
      "token": "İNSAN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 1.07
     },
     {
      "gloss": "HEPSİ",
      "token": "HEPSİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.038,
      "end": 1.612
     },
     {
      "gloss": "ALÇALMAK",
      "token": "ALÇALMAK",
      "strategy": "direct",
      "kind": "",
      "start": 1.58,
      "end": 2.112
     },
     {
      "gloss": "YAPMAK",
      "token": "YAPMAK",
      "strategy": "direct",
      "kind": "",
      "start": 2.08,
      "end": 2.612
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 2.455,
      "end": 2.82
     },
     {
      "gloss": "EŞİT",
      "token": "EŞİT",
      "strategy": "direct",
      "kind": "",
      "start": 2.997,
      "end": 3.57
     }
    ]
   },
   "reference": {
    "video": "media/reference/1687-02.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_1917-02",
  "sample_id": "1917-02",
  "turkish": "Benim gözlerim mavi, saçlarım sarı olduğu için arkadaşlarım sürekli Alman mısın? diye soruyorlar. Ben de onlara hayır Türkiye'de doğdum (Türküm) diyorum.",
  "category": "plain",
  "reference_gloss": "BENİM GÖZ MAVİ SAÇ SARI ARKADAŞ SORMAK SEN ALMANYA DOĞMAK? BEN YOK TÜRKİYE DEMEK",
  "predicted_gloss": "BEN GÖZ MAVİ SAÇ SARI ARKADAŞ ALMAN? ALMAN? SORMAK SORMAK BEN HAYIR TÜRKİYE DOĞMAK TÜRK BEN",
  "rewritten_gloss": "BEN GÖZ MAVİ SAÇ SARI ARKADAŞ ALMAN? ALMAN? SORMAK SORMAK BEN HAYIR TÜRKİYE DOĞMAK TÜRK BEN",
  "conditions": {
   "avatar": {
    "video": "media/avatar/1917-02.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "GÖZ",
      "token": "GÖZ",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.487
     },
     {
      "gloss": "MAVİ",
      "token": "MAVİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.663,
      "end": 2.195
     },
     {
      "gloss": "SAÇ",
      "token": "SAÇ",
      "strategy": "direct",
      "kind": "",
      "start": 2.163,
      "end": 2.778
     },
     {
      "gloss": "SARI",
      "token": "SARI",
      "strategy": "direct",
      "kind": "",
      "start": 2.747,
      "end": 3.278
     },
     {
      "gloss": "ARKADAŞ",
      "token": "ARKADAŞ",
      "strategy": "direct",
      "kind": "",
      "start": 3.247,
      "end": 3.82
     },
     {
      "gloss": "ALMAN?",
      "token": "ALMAN?",
      "strategy": "direct",
      "kind": "",
      "start": 3.997,
      "end": 4.903
     },
     {
      "gloss": "SORMAK",
      "token": "SORMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.872,
      "end": 5.862
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 6.038,
      "end": 6.57
     },
     {
      "gloss": "HAYIR",
      "token": "HAYIR",
      "strategy": "direct",
      "kind": "",
      "start": 6.538,
      "end": 7.07
     },
     {
      "gloss": "TÜRKİYE",
      "token": "TÜRKİYE",
      "strategy": "direct",
      "kind": "",
      "start": 7.038,
      "end": 7.57
     },
     {
      "gloss": "DOĞMAK",
      "token": "DOĞMAK",
      "strategy": "direct",
      "kind": "",
      "start": 7.538,
      "end": 8.07
     },
     {
      "gloss": "TÜRK",
      "token": "TÜRK",
      "strategy": "direct",
      "kind": "",
      "start": 8.038,
      "end": 8.57
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 8.538,
      "end": 9.112
     }
    ]
   },
   "reference": {
    "video": "media/reference/1917-02.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_241-06",
  "sample_id": "241-06",
  "turkish": "Bugün sevgilimle yıl dönümümüz. Bir cafe bulmuş ve bana sürpriz yapmak için orayı bizim için kapatmış. İçeri girdiğimde hiç kimse yoktu, içerisi bomboştu.",
  "category": "oov",
  "reference_gloss": "BEN SEVGİLİ BUGÜN SEVGİLİ GÜN O SEVGİLİ BULMAK BİR CAFE GİTMEK PARA ÖDEMEK HEP KİŞİ BOŞ HEPSİ KAPATMAK BEN SEVGİLİ BERABER GİTMEK HEP KİŞİ BOŞ BEN İÇİN BEN SÜRPRİZ YAPMAK",
  "predicted_gloss": "BUGÜN SEVGİLİ YIL DÖNÜM VAR SEVGİLİ SÜRPRİZ CAFE GİTMEK KİŞİ HEPSİ SIFIR (BOŞ) SEVGİLİ SÜRPRİZ BEN GİTMEK",
  "rewritten_gloss": "BUGÜN SEVGİLİ YIL DÖNÜM VAR SEVGİLİ SÜRPRİZ CAFE GİTMEK KİŞİ HEPSİ SIFIR BOŞ SEVGİLİ SÜRPRİZ BEN GİTMEK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/241-06.mp4",
    "segments": [
     {
      "gloss": "BUGÜN",
      "token": "BUGÜN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "SEVGİLİ",
      "token": "SEVGİLİ",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "YIL",
      "token": "YIL",
      "strategy": "lexicon-alternative",
      "kind": "oov",
      "start": 1.413,
      "end": 1.945
     },
     {
      "gloss": "D-Ö-N-Ü-M",
      "token": "DÖNÜM",
      "strategy": "fingerspell",
      "kind": "fs",
      "start": 1.872,
      "end": 3.737
     },
     {
      "gloss": "VAR",
      "token": "VAR",
      "strategy": "direct",
      "kind": "",
      "start": 3.663,
      "end": 4.237
     },
     {
      "gloss": "SEVGİLİ",
      "token": "SEVGİLİ",
      "strategy": "direct",
      "kind": "",
      "start": 4.413,
      "end": 4.945
     },
     {
      "gloss": "SÜRPRİZ",
      "token": "SÜRPRİZ",
      "strategy": "direct",
      "kind": "",
      "start": 4.913,
      "end": 5.487
     },
     {
      "gloss": "CAFE",
      "token": "CAFE",
      "strategy": "orthographic-loan",
      "kind": "",
      "start": 5.455,
      "end": 5.987
     },
     {
      "gloss": "GİTMEK",
      "token": "GİTMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 5.955,
      "end": 6.528
     },
     {
      "gloss": "KİŞİ",
      "token": "KİŞİ",
      "strategy": "direct",
      "kind": "",
      "start": 6.705,
      "end": 7.237
     },
     {
      "gloss": "HEPSİ",
      "token": "HEPSİ",
      "strategy": "direct",
      "kind": "",
      "start": 7.205,
      "end": 7.778
     },
     {
      "gloss": "SIFIR",
      "token": "SIFIR",
      "strategy": "direct",
      "kind": "",
      "start": 7.747,
      "end": 8.278
     },
     {
      "gloss": "BOŞ",
      "token": "BOŞ",
      "strategy": "direct",
      "kind": "",
      "start": 8.247,
      "end": 8.778
     },
     {
      "gloss": "SEVGİLİ",
      "token": "SEVGİLİ",
      "strategy": "direct",
      "kind": "",
      "start": 8.747,
      "end": 9.278
     },
     {
      "gloss": "SÜRPRİZ",
      "token": "SÜRPRİZ",
      "strategy": "direct",
      "kind": "",
      "start": 9.247,
      "end": 9.82
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 9.788,
      "end": 10.32
     },
     {
      "gloss": "GİTMEK",
      "token": "GİTMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 10.288,
      "end": 10.862
     }
    ]
   },
   "reference": {
    "video": "media/reference/241-06.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_280-04",
  "sample_id": "280-04",
  "turkish": "O adam çok okuyan, kültürlü bir kişi.",
  "category": "plain",
  "reference_gloss": "BİR ADAM O KİŞİ ÇOK OKUMAK ÇOK KÜLTÜR KİŞİ",
  "predicted_gloss": "O ADAM KİŞİ OKUMAK KÜLTÜR BİLMEK ÇOK FAZLA",
  "rewritten_gloss": "O ADAM KİŞİ OKUMAK KÜLTÜR BİLMEK ÇOK FAZLA",
  "conditions": {
   "avatar": {
    "video": "media/avatar/280-04.mp4",
    "segments": [
     {
      "gloss": "O",
      "token": "O",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.987
     },
     {
      "gloss": "ADAM",
      "token": "ADAM",
      "strategy": "direct",
      "kind": "",
      "start": 0.955,
      "end": 1.612
     },
     {
      "gloss": "KİŞİ",
      "token": "KİŞİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.58,
      "end": 2.153
     },
     {
      "gloss": "OKUMAK",
      "token": "OKUMAK",
      "strategy": "direct",
      "kind": "",
      "start": 2.33,
      "end": 2.862
     },
     {
      "gloss": "KÜLTÜR",
      "token": "KÜLTÜR",
      "strategy": "direct",
      "kind": "",
      "start": 2.83,
      "end": 3.362
     },
     {
      "gloss": "BİLMEK",
      "token": "BİLMEK",
      "strategy": "direct",
      "kind": "",
      "start": 3.538,
      "end": 4.07
     },
     {
      "gloss": "ÇOK",
      "token": "ÇOK",
      "strategy": "direct",
      "kind": "",
      "start": 4.247,
      "end": 4.778
     },
     {
      "gloss": "FAZLA",
      "token": "FAZLA",
      "strategy": "direct",
      "kind": "",
      "start": 4.747,
      "end": 5.32
     }
    ]
   },
   "reference": {
    "video": "media/reference/280-04.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_299-01",
  "sample_id": "299-01",
  "turkish": "Öğretmenin verdiği tarih ödevini kütüphanede ararştırarak bulabildim.",
  "category": "agreement",
  "reference_gloss": "ÖĞRETMEN BEN TARİH ÖDEV VERMEK BEN KÜTÜPHANE GİTMEK KİTAP BAKMAK ARAŞTIRMAK ARAŞTIRMAK BULMAK BULMAK",
  "predicted_gloss": "ÖĞRETMEN TARİH ÖDEV VERMEK BEN KÜTÜPHANE GİTMEK ARAŞTIRMAK ARAŞTIRMAK BULMAK",
  "rewritten_gloss": "ÖĞRETMEN TARİH IX3a ÖDEV IX3b 3aVERMEK3b BEN KÜTÜPHANE GİTMEK ARAŞTIRMAK ARAŞTIRMAK BULMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/299-01.mp4",
    "segments": [
     {
      "gloss": "ÖĞRETMEN",
      "token": "ÖĞRETMEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "TARİH",
      "token": "TARİH",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "İŞARET ET (3a)",
      "token": "IX3a",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 1.413,
      "end": 1.862
     },
     {
      "gloss": "ÖDEV",
      "token": "ÖDEV",
      "strategy": "direct",
      "kind": "",
      "start": 1.83,
      "end": 2.445
     },
     {
      "gloss": "İŞARET ET (3b)",
      "token": "IX3b",
      "strategy": "synth-ix",
      "kind": "agr",
      "start": 2.413,
      "end": 2.862
     },
     {
      "gloss": "VERMEK (3a→3b)",
      "token": "3aVERMEK3b",
      "strategy": "synth-agr",
      "kind": "agr",
      "start": 2.83,
      "end": 3.57
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 3.747,
      "end": 4.278
     },
     {
      "gloss": "KÜTÜPHANE",
      "token": "KÜTÜPHANE",
      "strategy": "hane-compound",
      "kind": "",
      "start": 4.247,
      "end": 4.862
     },
     {
      "gloss": "GİTMEK",
      "token": "GİTMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 4.83,
      "end": 5.362
     },
     {
      "gloss": "ARAŞTIRMAK",
      "token": "ARAŞTIRMAK",
      "strategy": "direct",
      "kind": "",
      "start": 5.33,
      "end": 6.237
     },
     {
      "gloss": "BULMAK",
      "token": "BULMAK",
      "strategy": "direct",
      "kind": "",
      "start": 6.205,
      "end": 6.778
     }
    ]
   },
   "reference": {
    "video": "media/reference/299-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_486-03",
  "sample_id": "486-03",
  "turkish": "Yarın iki dersten sınavım var. Mecburen çok çalışacağım.",
  "category": "plain",
  "reference_gloss": "YARIN (ÇİFT) İKİ DERS SINAV VAR MECBUR BEN ÇALIŞMAK ÇALIŞMAK Yarın iki dersten sınavım var. Mecburen çok çalışacağım.",
  "predicted_gloss": "YARIN OKUL İKİ DERSE SINAV VAR MECBUR ÇALIŞMAK ÇALIŞMAK",
  "rewritten_gloss": "YARIN OKUL İKİ DERSE SINAV VAR MECBUR ÇALIŞMAK ÇALIŞMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/486-03.mp4",
    "segments": [
     {
      "gloss": "YARIN",
      "token": "YARIN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "OKUL",
      "token": "OKUL",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "İKİ",
      "token": "İKİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 1.945
     },
     {
      "gloss": "DERSE",
      "token": "DERSE",
      "strategy": "morphological",
      "kind": "",
      "start": 1.913,
      "end": 2.445
     },
     {
      "gloss": "SINAV",
      "token": "SINAV",
      "strategy": "direct",
      "kind": "",
      "start": 2.413,
      "end": 2.945
     },
     {
      "gloss": "VAR",
      "token": "VAR",
      "strategy": "direct",
      "kind": "",
      "start": 2.913,
      "end": 3.487
     },
     {
      "gloss": "MECBUR",
      "token": "MECBUR",
      "strategy": "direct",
      "kind": "",
      "start": 3.663,
      "end": 4.195
     },
     {
      "gloss": "ÇALIŞMAK",
      "token": "ÇALIŞMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.163,
      "end": 5.153
     }
    ]
   },
   "reference": {
    "video": "media/reference/486-03.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_492-03",
  "sample_id": "492-03",
  "turkish": "Arkadaşımın kötü hiçbir huyu yok. Çok temiz biri, ona çok güveniyorum.",
  "category": "plain",
  "reference_gloss": "BEN BİR ARKADAŞ SAPIK HAPİS KÖTÜ ÇEŞİT YOK KİŞİ TEMİZ BEN GÜVENMEK",
  "predicted_gloss": "BEN ARKADAŞ O KİŞİ KÖTÜ HİÇ TEMİZ GÜVENMEK",
  "rewritten_gloss": "BEN ARKADAŞ O KİŞİ KÖTÜ HİÇ TEMİZ GÜVENMEK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/492-03.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "ARKADAŞ",
      "token": "ARKADAŞ",
      "strategy": "direct",
      "kind": "",
      "start": 0.788,
      "end": 1.32
     },
     {
      "gloss": "O",
      "token": "O",
      "strategy": "direct",
      "kind": "",
      "start": 1.288,
      "end": 1.862
     },
     {
      "gloss": "KİŞİ",
      "token": "KİŞİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.83,
      "end": 2.362
     },
     {
      "gloss": "KÖTÜ",
      "token": "KÖTÜ",
      "strategy": "direct",
      "kind": "",
      "start": 2.33,
      "end": 2.862
     },
     {
      "gloss": "HİÇ",
      "token": "HİÇ",
      "strategy": "direct",
      "kind": "",
      "start": 2.83,
      "end": 3.403
     },
     {
      "gloss": "TEMİZ",
      "token": "TEMİZ",
      "strategy": "direct",
      "kind": "",
      "start": 3.58,
      "end": 4.153
     },
     {
      "gloss": "GÜVENMEK",
      "token": "GÜVENMEK",
      "strategy": "direct",
      "kind": "",
      "start": 4.122,
      "end": 4.695
     }
    ]
   },
   "reference": {
    "video": "media/reference/492-03.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_573-04",
  "sample_id": "573-04",
  "turkish": "Dernek kongresinde aday olan iki kişi vardı ve puanları da aynı olunca ikisinin birleşerek birlikte çalışmasına karar verildi.",
  "category": "oov",
  "reference_gloss": "DERNEK KONGRE VAR SAĞIR ADAY BİR GELMEK AYNI ADAY BAŞKA BİR GELMEK OY PUAN AYNI NE YAPMAK TOPLUM HEPSİ EL KALDIRMAK İKİSİ BİRLEŞMEK ÇALIŞMAK DEVAM ETMEK",
  "predicted_gloss": "DERNEK KONGRE İKİ KİŞİ ADAY OLMAK PUAN AYNI BERABERE OLMAK İKİ KİŞİ BİRLEŞMEK BERABER ÇALIŞMAK",
  "rewritten_gloss": "DERNEK KONGRE İKİ KİŞİ ADAY OLMAK PUAN AYNI BERABERE OLMAK İKİ KİŞİ BİRLEŞMEK BERABER ÇALIŞMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/573-04.mp4",
    "segments": [
     {
      "gloss": "DERNEK",
      "token": "DERNEK",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "KONGRE",
      "token": "KONGRE",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "İKİ",
      "token": "İKİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 1.945
     },
     {
      "gloss": "KİŞİ",
      "token": "KİŞİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.913,
      "end": 2.445
     },
     {
      "gloss": "ADAY",
      "token": "ADAY",
      "strategy": "direct",
      "kind": "",
      "start": 2.413,
      "end": 2.945
     },
     {
      "gloss": "OLMAK",
      "token": "OLMAK",
      "strategy": "direct",
      "kind": "",
      "start": 2.913,
      "end": 3.445
     },
     {
      "gloss": "PUAN",
      "token": "PUAN",
      "strategy": "direct",
      "kind": "",
      "start": 3.413,
      "end": 3.945
     },
     {
      "gloss": "AYNI",
      "token": "AYNI",
      "strategy": "direct",
      "kind": "",
      "start": 3.913,
      "end": 4.445
     },
     {
      "gloss": "BERABERE",
      "token": "BERABERE",
      "strategy": "morphological",
      "kind": "",
      "start": 4.413,
      "end": 4.945
     },
     {
      "gloss": "OLMAK",
      "token": "OLMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.913,
      "end": 5.487
     },
     {
      "gloss": "İKİ",
      "token": "İKİ",
      "strategy": "direct",
      "kind": "",
      "start": 5.663,
      "end": 6.195
     },
     {
      "gloss": "KİŞİ",
      "token": "KİŞİ",
      "strategy": "direct",
      "kind": "",
      "start": 6.163,
      "end": 6.695
     },
     {
      "gloss": "BİRLEŞMEK",
      "token": "BİRLEŞMEK",
      "strategy": "sense",
      "kind": "oov",
      "start": 6.663,
      "end": 7.237
     },
     {
      "gloss": "BERABER",
      "token": "BERABER",
      "strategy": "direct",
      "kind": "",
      "start": 7.205,
      "end": 7.737
     },
     {
      "gloss": "ÇALIŞMAK",
      "token": "ÇALIŞMAK",
      "strategy": "direct",
      "kind": "",
      "start": 7.705,
      "end": 8.278
     }
    ]
   },
   "reference": {
    "video": "media/reference/573-04.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_63-01",
  "sample_id": "63-01",
  "turkish": "Dostumun iki kızı var.",
  "category": "plain",
  "reference_gloss": "BEN DOST İKİ KIZ ÇOCUK VAR",
  "predicted_gloss": "BEN DOST İKİ KIZ VAR",
  "rewritten_gloss": "BEN DOST İKİ KIZ VAR",
  "conditions": {
   "avatar": {
    "video": "media/avatar/63-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "DOST",
      "token": "DOST",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "İKİ",
      "token": "İKİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 1.945
     },
     {
      "gloss": "KIZ",
      "token": "KIZ",
      "strategy": "direct",
      "kind": "",
      "start": 1.913,
      "end": 2.445
     },
     {
      "gloss": "VAR",
      "token": "VAR",
      "strategy": "direct",
      "kind": "",
      "start": 2.413,
      "end": 2.987
     }
    ]
   },
   "reference": {
    "video": "media/reference/63-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_78-01",
  "sample_id": "78-01",
  "turkish": "Ben cümle kurmakta iyi değilim ancak kız kardeşim çok iyi biliyor.",
  "category": "plain",
  "reference_gloss": "CÜMLE BEN YAZMAK NORMAL (EH) KIZ KARDEŞ HEPSİ BİLMEK",
  "predicted_gloss": "BEN CÜMLE KURMAK İYİ^DEĞİL AMA KARDEŞ KIZ CÜMLE KURMAK ÇOK İYİ",
  "rewritten_gloss": "BEN CÜMLE KURMAK İYİ DEĞİL AMA KARDEŞ KIZ CÜMLE KURMAK ÇOK İYİ",
  "conditions": {
   "avatar": {
    "video": "media/avatar/78-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "CÜMLE",
      "token": "CÜMLE",
      "strategy": "lexicon-alternative",
      "kind": "oov",
      "start": 0.913,
      "end": 1.445
     },
     {
      "gloss": "KURMAK",
      "token": "KURMAK",
      "strategy": "direct",
      "kind": "",
      "start": 1.413,
      "end": 1.945
     },
     {
      "gloss": "İYİ",
      "token": "İYİ",
      "strategy": "direct",
      "kind": "",
      "start": 1.913,
      "end": 2.445
     },
     {
      "gloss": "DEĞİL",
      "token": "DEĞİL",
      "strategy": "direct",
      "kind": "",
      "start": 2.288,
      "end": 2.695
     },
     {
      "gloss": "AMA",
      "token": "AMA",
      "strategy": "direct",
      "kind": "",
      "start": 2.872,
      "end": 3.403
     },
     {
      "gloss": "KARDEŞ",
      "token": "KARDEŞ",
      "strategy": "direct",
      "kind": "",
      "start": 3.372,
      "end": 3.903
     },
     {
      "gloss": "KIZ",
      "token": "KIZ",
      "strategy": "direct",
      "kind": "",
      "start": 3.872,
      "end": 4.403
     },
     {
      "gloss": "CÜMLE",
      "token": "CÜMLE",
      "strategy": "lexicon-alternative",
      "kind": "oov",
      "start": 4.372,
      "end": 4.903
     },
     {
      "gloss": "KURMAK",
      "token": "KURMAK",
      "strategy": "direct",
      "kind": "",
      "start": 4.872,
      "end": 5.403
     },
     {
      "gloss": "ÇOK",
      "token": "ÇOK",
      "strategy": "direct",
      "kind": "",
      "start": 5.372,
      "end": 5.903
     },
     {
      "gloss": "İYİ",
      "token": "İYİ",
      "strategy": "direct",
      "kind": "",
      "start": 5.872,
      "end": 6.445
     }
    ]
   },
   "reference": {
    "video": "media/reference/78-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_820-01",
  "sample_id": "820-01",
  "turkish": "Güvenliğimiz olmadığı için evime sürekli hırsız giriyor bu nedenle bende güvenliği, kamera sistemi olan bir siteye taşındım ama birgün buraya da hırsız girdi. Çünkü, güvenlik görevlisi sorumluluğunu yerine getirmemişti. Sonra polisler geldi ve bizler de ifade verdik.",
  "category": "oov",
  "reference_gloss": "BENİM EV HIRSIZ GİRMEK GİRMEK FAZLA SEBEP GÜVENLİK YOK YÜZDEN BEN EV TAŞINMAK YER O SİTE YER GÜVENLİK HAZIR KAMERA HAZIR BEN RAHAT OTURMAK SONRA SONRA HIRSIZ GİRMEK BEN ŞAŞIRMAK KİM GÜVENLİK TAM SORUMLU O BEN GİTMEK HESAP SORMAK SORMAK KONUŞMAK KONUŞMAK",
  "predicted_gloss": "BEN EV GÜVENLİK YOK HIRSIZ GİRMEK GİRMEK BEN SİTE TAŞINMAK GÜVENLİK VAR AMA BİR GÜN HIRSIZ GİRMEK GÜVENLİK SORUMLULUK BOŞVERMEK GÜVENLİK",
  "rewritten_gloss": "BEN EV GÜVENLİK YOK HIRSIZ GİRMEK GİRMEK BEN SİTE TAŞINMAK GÜVENLİK VAR AMA BİR GÜN HIRSIZ GİRMEK GÜVENLİK SORUMLULUK BOŞVERMEK GÜVENLİK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/820-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "EV",
      "token": "EV",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.487
     },
     {
      "gloss": "GÜVENLİK",
      "token": "GÜVENLİK",
      "strategy": "direct",
      "kind": "",
      "start": 1.455,
      "end": 1.987
     },
     {
      "gloss": "YOK",
      "token": "YOK",
      "strategy": "direct",
      "kind": "",
      "start": 1.955,
      "end": 2.57
     },
     {
      "gloss": "HIRSIZ",
      "token": "HIRSIZ",
      "strategy": "direct",
      "kind": "",
      "start": 2.538,
      "end": 3.07
     },
     {
      "gloss": "GİRMEK",
      "token": "GİRMEK",
      "strategy": "direct",
      "kind": "",
      "start": 3.038,
      "end": 4.028
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 4.205,
      "end": 4.737
     },
     {
      "gloss": "S-İ-T-E",
      "token": "SİTE",
      "strategy": "fingerspell",
      "kind": "fs",
      "start": 4.663,
      "end": 6.195
     },
     {
      "gloss": "TAŞINMAK",
      "token": "TAŞINMAK",
      "strategy": "direct",
      "kind": "",
      "start": 6.122,
      "end": 6.695
     },
     {
      "gloss": "GÜVENLİK",
      "token": "GÜVENLİK",
      "strategy": "direct",
      "kind": "",
      "start": 6.663,
      "end": 7.195
     },
     {
      "gloss": "VAR",
      "token": "VAR",
      "strategy": "direct",
      "kind": "",
      "start": 7.163,
      "end": 7.737
     },
     {
      "gloss": "AMA",
      "token": "AMA",
      "strategy": "direct",
      "kind": "",
      "start": 7.913,
      "end": 8.445
     },
     {
      "gloss": "BİR",
      "token": "BİR",
      "strategy": "direct",
      "kind": "",
      "start": 8.413,
      "end": 8.945
     },
     {
      "gloss": "GÜN",
      "token": "GÜN",
      "strategy": "sense",
      "kind": "oov",
      "start": 8.913,
      "end": 9.445
     },
     {
      "gloss": "HIRSIZ",
      "token": "HIRSIZ",
      "strategy": "direct",
      "kind": "",
      "start": 9.413,
      "end": 9.945
     },
     {
      "gloss": "GİRMEK",
      "token": "GİRMEK",
      "strategy": "direct",
      "kind": "",
      "start": 9.913,
      "end": 10.487
     },
     {
      "gloss": "GÜVENLİK",
      "token": "GÜVENLİK",
      "strategy": "direct",
      "kind": "",
      "start": 10.455,
      "end": 10.987
     },
     {
      "gloss": "SORUMLULUK",
      "token": "SORUMLULUK",
      "strategy": "root-finder",
      "kind": "oov",
      "start": 10.955,
      "end": 11.528
     },
     {
      "gloss": "BOŞVERMEK",
      "token": "BOŞVERMEK",
      "strategy": "direct",
      "kind": "",
      "start": 11.497,
      "end": 12.07
     },
     {
      "gloss": "GÜVENLİK",
      "token": "GÜVENLİK",
      "strategy": "direct",
      "kind": "",
      "start": 12.247,
      "end": 12.82
     }
    ]
   },
   "reference": {
    "video": "media/reference/820-01.mp4",
    "segments": []
   }
  }
 },
 {
  "id": "it_948-01",
  "sample_id": "948-01",
  "turkish": "Evdeki bilgisayarı kimin kullanacağı konusunda kardeşimle sürekli rekabet halindeydik. En iyisi saatli kullanmak diye karar verdik ve sabahları sen kullan akşamları ben kullanayım dedim. O da kabul edince sorun çözüldü.",
  "category": "oov",
  "reference_gloss": "EV BİLGİSAYAR VAR KARDEŞ REKABET REKABET BEN UZATMAK^DEĞİL KISA SAAT PROGRAM KOYMAK SABAH ONUN AKŞAM BENİM TAM KONUŞMAK ANLAŞMAK KAPANMAK",
  "predicted_gloss": "BEN EV BİLGİSAYAR KİM KULLANMAK KİM KULLANMAK KARDEŞ REKABET REKABET EN İYİ SAAT SAAT KULLANMAK KARAR VERMEK BEN SABAH KULLANMAK AKŞAM KARDEŞ KULLANMAK",
  "rewritten_gloss": "BEN EV BİLGİSAYAR KİM KULLANMAK KİM KULLANMAK KARDEŞ REKABET REKABET EN İYİ SAAT SAAT KULLANMAK KARAR VERMEK BEN SABAH KULLANMAK AKŞAM KARDEŞ KULLANMAK",
  "conditions": {
   "avatar": {
    "video": "media/avatar/948-01.mp4",
    "segments": [
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 0.413,
      "end": 0.945
     },
     {
      "gloss": "EV",
      "token": "EV",
      "strategy": "direct",
      "kind": "",
      "start": 0.913,
      "end": 1.487
     },
     {
      "gloss": "BİLGİSAYAR",
      "token": "BİLGİSAYAR",
      "strategy": "direct",
      "kind": "",
      "start": 1.455,
      "end": 2.112
     },
     {
      "gloss": "KİM",
      "token": "KİM",
      "strategy": "direct",
      "kind": "",
      "start": 2.08,
      "end": 2.612
     },
     {
      "gloss": "KULLANMAK",
      "token": "KULLANMAK",
      "strategy": "direct",
      "kind": "",
      "start": 2.58,
      "end": 3.112
     },
     {
      "gloss": "KİM",
      "token": "KİM",
      "strategy": "direct",
      "kind": "",
      "start": 3.08,
      "end": 3.612
     },
     {
      "gloss": "KULLANMAK",
      "token": "KULLANMAK",
      "strategy": "direct",
      "kind": "",
      "start": 3.58,
      "end": 4.112
     },
     {
      "gloss": "KARDEŞ",
      "token": "KARDEŞ",
      "strategy": "direct",
      "kind": "",
      "start": 4.08,
      "end": 4.612
     },
     {
      "gloss": "REKABET",
      "token": "REKABET",
      "strategy": "direct",
      "kind": "",
      "start": 4.58,
      "end": 5.487
     },
     {
      "gloss": "EN",
      "token": "EN",
      "strategy": "direct",
      "kind": "",
      "start": 5.455,
      "end": 5.987
     },
     {
      "gloss": "İYİ",
      "token": "İYİ",
      "strategy": "direct",
      "kind": "",
      "start": 5.913,
      "end": 6.445
     },
     {
      "gloss": "SAAT",
      "token": "SAAT",
      "strategy": "sense",
      "kind": "oov",
      "start": 6.413,
      "end": 7.32
     },
     {
      "gloss": "KULLANMAK",
      "token": "KULLANMAK",
      "strategy": "direct",
      "kind": "",
      "start": 7.288,
      "end": 7.82
     },
     {
      "gloss": "KARAR VERMEK",
      "token": "KARAR VERMEK",
      "strategy": "direct",
      "kind": "",
      "start": 7.788,
      "end": 8.362
     },
     {
      "gloss": "BEN",
      "token": "BEN",
      "strategy": "direct",
      "kind": "",
      "start": 8.538,
      "end": 9.07
     },
     {
      "gloss": "SABAH",
      "token": "SABAH",
      "strategy": "direct",
      "kind": "",
      "start": 9.038,
      "end": 9.57
     },
     {
      "gloss": "KULLANMAK",
      "token": "KULLANMAK",
      "strategy": "direct",
      "kind": "",
      "start": 9.538,
      "end": 10.07
     },
     {
      "gloss": "AKŞAM",
      "token": "AKŞAM",
      "strategy": "direct",
      "kind": "",
      "start": 10.038,
      "end": 10.653
     },
     {
      "gloss": "KARDEŞ",
      "token": "KARDEŞ",
      "strategy": "direct",
      "kind": "",
      "start": 10.622,
      "end": 11.153
     },
     {
      "gloss": "KULLANMAK",
      "token": "KULLANMAK",
      "strategy": "direct",
      "kind": "",
      "start": 11.122,
      "end": 11.695
     }
    ]
   },
   "reference": {
    "video": "media/reference/948-01.mp4",
    "segments": []
   }
  }
 }
];
window.STUDY.pairs = [
 {
  "id": "pair_1003-03",
  "itemId": "it_1003-03",
  "ablation": "no_agreement",
  "turkish": "Ben müzik öğretmeniyim, ilkokul öğrencilerine derste flütü nasıl üfleyeceklerini anlattım.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1003-03.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/1003-03_no_agreement.mp4"
  }
 },
 {
  "id": "pair_1026-02",
  "itemId": "it_1026-02",
  "ablation": "no_agreement",
  "turkish": "Arkadaşım beni evine davet etti. İki odalı, dar bir evde oturuyor. Sıkışarak oturabildik. Ben bu kadar dar bir evde oturamam.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1026-02.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/1026-02_no_agreement.mp4"
  }
 },
 {
  "id": "pair_1052-03",
  "itemId": "it_1052-03",
  "ablation": "no_agreement",
  "turkish": "Kar yağdığında çocuğun biri sürekli bana kar topu atıyordu, çok sinir oldum ve ona nişan alarak kar tapu ile onu tam hedeften vurdum.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1052-03.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/1052-03_no_agreement.mp4"
  }
 },
 {
  "id": "pair_1201-01",
  "itemId": "it_1201-01",
  "ablation": "no_agreement",
  "turkish": "Tiyatro oyunumuz için on iki kişilik bir takım oluşturduk ve oyuna çalıştırdık. Herkes hazır olunca da insanları davet edip oyunumuzu sunduk.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1201-01.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/1201-01_no_agreement.mp4"
  }
 },
 {
  "id": "pair_1217-01",
  "itemId": "it_1217-01",
  "ablation": "no_agreement",
  "turkish": "Oğlum yüzmeyi bilmediği için sürekli batıyordu, şimdi ona öğrettim ve çok güzel yüzüyor.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1217-01.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/1217-01_no_agreement.mp4"
  }
 },
 {
  "id": "pair_1330-01",
  "itemId": "it_1330-01",
  "ablation": "no_agreement",
  "turkish": "Kız kardeşim evlenirken damat tarafı gelin almaya geldiği zaman, kırmızı kurdele bağlandıktan sonra onu (evden) çıkardık.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1330-01.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/1330-01_no_agreement.mp4"
  }
 },
 {
  "id": "pair_1406-02",
  "itemId": "it_1406-02",
  "ablation": "no_ctx_oov",
  "turkish": "İşaret dilini öğrendikten sonra, öğretmenlik yapmaya başladım ve ilk ayak bastığım yer kolej oldu.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1406-02.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/1406-02_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_1467-01",
  "itemId": "it_1467-01",
  "ablation": "no_ctx_oov",
  "turkish": "Arabamı temizlettikten sonra üzerini bezle örttüm. Yakında düğün var, kirlenmesini istemiyorum.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1467-01.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/1467-01_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_1503-01",
  "itemId": "it_1503-01",
  "ablation": "no_ctx_oov",
  "turkish": "Odadan henüz çıkmıştım ki, arkamdam birçok olay olmuş. Döndüğümde olanları anlattılar, ağzım açık kaldı.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1503-01.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/1503-01_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_1672-02",
  "itemId": "it_1672-02",
  "ablation": "no_ctx_oov",
  "turkish": "Arkadaşlarla birlikte Rize'ye gittik ve hep birlikte yaylaya çıktık. Havası ve manzarası çok güzeldi.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/1672-02.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/1672-02_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_241-06",
  "itemId": "it_241-06",
  "ablation": "no_ctx_oov",
  "turkish": "Bugün sevgilimle yıl dönümümüz. Bir cafe bulmuş ve bana sürpriz yapmak için orayı bizim için kapatmış. İçeri girdiğimde hiç kimse yoktu, içerisi bomboştu.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/241-06.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/241-06_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_299-01",
  "itemId": "it_299-01",
  "ablation": "no_agreement",
  "turkish": "Öğretmenin verdiği tarih ödevini kütüphanede ararştırarak bulabildim.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/299-01.mp4"
  },
  "b": {
   "label": "no_agreement",
   "video": "media/ablation/299-01_no_agreement.mp4"
  }
 },
 {
  "id": "pair_573-04",
  "itemId": "it_573-04",
  "ablation": "no_ctx_oov",
  "turkish": "Dernek kongresinde aday olan iki kişi vardı ve puanları da aynı olunca ikisinin birleşerek birlikte çalışmasına karar verildi.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/573-04.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/573-04_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_820-01",
  "itemId": "it_820-01",
  "ablation": "no_ctx_oov",
  "turkish": "Güvenliğimiz olmadığı için evime sürekli hırsız giriyor bu nedenle bende güvenliği, kamera sistemi olan bir siteye taşındım ama birgün buraya da hırsız girdi. Çünkü, güvenlik görevlisi sorumluluğunu yerine getirmemişti. Sonra polisler geldi ve bizler de ifade verdik.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/820-01.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/820-01_no_ctx_oov.mp4"
  }
 },
 {
  "id": "pair_948-01",
  "itemId": "it_948-01",
  "ablation": "no_ctx_oov",
  "turkish": "Evdeki bilgisayarı kimin kullanacağı konusunda kardeşimle sürekli rekabet halindeydik. En iyisi saatli kullanmak diye karar verdik ve sabahları sen kullan akşamları ben kullanayım dedim. O da kabul edince sorun çözüldü.",
  "figure": "avatar",
  "a": {
   "label": "full",
   "video": "media/avatar/948-01.mp4"
  },
  "b": {
   "label": "no_ctx_oov",
   "video": "media/ablation/948-01_no_ctx_oov.mp4"
  }
 }
];
