"""STUDY_V5_2026_10_05: rewrite stimuli.js for the final stimuli without re-rendering.
avatar = our pipeline on the Gemma 4 31B gloss (final navy renders), gold = same pipeline on the
gold gloss, reference = the real TİD Sözlük sentence video. Segments (replay buttons) come from
each sample's frame_info.json + tokens.json and the motion's playback timing; the renders start
with a 6-frame hold (offset 0.25 s at 24 fps).
  python signer_study/web/update_stimuli_v5.py"""
import json, re, csv, sys, time
from pathlib import Path
HERE = Path(__file__).resolve().parent; SS = HERE.parent; PROJ = SS.parent
sys.path[:0] = [str(SS), str(PROJ)]
from build_stimuli import display_label, seg_kind
OFFSET = 6 / 24.0

def segments(wdir):
    toks = json.loads((wdir / 'tokens.json').read_text())['tokens']
    info = json.loads((wdir / 'frame_info.json').read_text())
    pb = json.loads((wdir / 'motion_simple.json').read_text()).get('playback')
    if pb: info = [info[a if u < 0.5 else b] for a, b, u in pb]
    spans = {}
    for i, f in enumerate(info):
        ci = f.get('clip_idx')
        if f.get('type') == 'sign' and isinstance(ci, int) and ci >= 0:
            spans.setdefault(ci, [i, i])[1] = i
    out = []
    for ci in sorted(spans):
        if ci >= len(toks): continue
        a, b = spans[ci]; e = toks[ci]
        out.append({"gloss": display_label(e['token'], e['strategy']), "token": e['token'], "strategy": e['strategy'],
                    "kind": seg_kind(e['strategy']), "start": round(max(0.0, OFFSET + a / 24 - 0.12), 3),
                    "end": round(OFFSET + (b + 1) / 24 + 0.12, 3)})
    return out, ' '.join(t['token'] for t in toks)

s = (HERE / 'stimuli.js').read_text()
get = lambda name: json.loads(re.search(r'window.STUDY.' + name + r' = (\[.*?\n\]);', s, re.S).group(1))
items, practice, pairs = get('items'), get('practice'), get('pairs')
rows = {r['sample_id']: r for r in csv.DictReader(open(PROJ / 'rendering_attempts/gemma4_all25/study_items_gemma3_vs_gemma4.csv', encoding='utf-8-sig'))}
FIX = {'ALÇALTMAK': 'ALÇALMAK', 'ÇALIŞTIRMAK': 'ÇALIŞMAK', 'SUNMAK': 'GÖSTERMEK', 'GÖREVLİ': 'ADAM'}
for it in items:
    sid = it['sample_id']; w = SS / 'wan_inputs' / sid
    segs, rew = segments(w); gsegs, grew = segments(w / 'gold')
    it['predicted_gloss'] = ' '.join(FIX.get(t, t) for t in rows[sid]['gemma4_31b'].split())
    it['rewritten_gloss'] = rew
    it['conditions'] = {
        'avatar': {'video': f'media/avatar/{sid}.mp4', 'segments': segs},
        'gold': {'video': f'media/gold/{sid}.mp4', 'segments': gsegs, 'rewritten_gloss': grew},
        'reference': {'video': f'media/reference/{sid}.mp4', 'segments': []},
    }
# PRACTICE_2026_10_05 (Onur): 708-03 ("İneklerin hepsi koca kafalı.") had a loose corpus translation;
# the practice item is now the short test sentence 656-01 (Gemma 4 prediction = gold gloss)
practice = [{"id": "prac_656-01", "sample_id": "656-01", "turkish": "Bu akşam saat dokuzda buluşacağız.", "category": "plain",
             "reference_gloss": "BU AKŞAM SAAT DOKUZ BULUŞMAK", "predicted_gloss": "BU AKŞAM SAAT DOKUZ BULUŞMAK"}]
for it in practice:
    sid = it['sample_id']; segs, rew = segments(SS / 'wan_inputs' / sid)
    it['rewritten_gloss'] = rew
    it['conditions'] = {'avatar': {'video': f'media/avatar/{sid}.mp4', 'segments': segs}}
js = ("// Generated by update_stimuli_v5.py on " + time.strftime("%Y-%m-%d %H:%M") + ". Do not edit by hand.\n"
      "window.STUDY.design.block1Conditions = [\"avatar\"];\n"
      "window.STUDY.design.expertConditions = [\"avatar\", \"gold\", \"reference\"];\n"
      "window.STUDY.design.deafConditions = [\"avatar\", \"reference\"];\n"
      "window.STUDY.design.expertOurs = \"avatar\";\n"
      f"window.STUDY.practice = {json.dumps(practice, ensure_ascii=False, indent=1)};\n"
      f"window.STUDY.items = {json.dumps(items, ensure_ascii=False, indent=1)};\n"
      f"window.STUDY.pairs = {json.dumps(pairs, ensure_ascii=False, indent=1)};\n")
(HERE / 'stimuli.js').write_text(js, encoding='utf-8')
print('items', len(items), 'practice', len(practice), 'pairs (unchanged, self mode only)', len(pairs))
